
#cloud-config
package_update: true
package_upgrade: false

runcmd:
  - [bash, -lc, "echo 'Starting Docker installation'"]
  - [bash, -lc, "apt-get -o Acquire::ForceIPv4=true update"]
  - [bash, -lc, "DEBIAN_FRONTEND=noninteractive apt-get -o Acquire::ForceIPv4=true install -y docker.io"]
  - [systemctl, enable, --now, docker]
  - [usermod, -aG, docker, ubuntu]
